# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scientist Design
email: john@scientist.design
description: >
  We're a small design shop using Art & Science to change the game for brands, big and small.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scientist.design" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Destination
destination: _site

# Sass Compiler
sass:
 style: :compressed
