---
title: Scientist Design
url: http://scientist.design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: john@scientist.design
description: |
  We're a small design shop using Art & Science to change the game for brands, big and small.
baseurl: ''
markdown: kramdown
destination: _site
sass:
  style: :compressed
