---
title: Scientist Design
url: http://scientist.design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: |
  We're a small design shop using Art & Science to change the game for brands, big and small.
email: john@scientist.design
baseurl: 
markdown: kramdown
destination: _site
sass:
  style: compressed
