---
title: Scientist Design
url: http://scientist.design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: |
  A multi-disciplinary design shop using art & science to change the game for brands on the internet and in real life.
email: john@scientist.design
baseurl:
markdown: kramdown
destination: _site
sass:
  style: compressed
